### ISSUE TITLE
Genericアバターでは設定時にエラーが発生する

### ISSUE THREAD

**Issue by Yumuru** [vr-voyage/vrchat-worldlock-autosetup#1]
**現象**
GenericアバターでConstrains World Lock Setupの適用ボタンを押したとき、
(既にFX Layerなどを設定済みアバター)
io.gthub.vr-voyage.tool.world-lock-autosetup/Editor/Constrains/SetupAvatarConstrains.cs:438
にてIndexOutOfRangeExceptionが発生する。
調べてみると、この例外はAvatarGetFXLayerメソッド内でavatar.baseAnimationLayers[FXLayerIndex()]を実行したときに発生している。

**原因**
VRC Avatar DescriptorのPlayable LayersのBaseの項目が違い、Humanoidでは5つ、Genericでは3つで、
FXLayerのインデックスもHumanoidでは5つ目だが、Genericでは3つ目と異なるために正しくFX Layerのアニメーターが取得できない。

**Comment by vr-voyage** [comment]
なるほど
結局、Generic系で、SDKが要らないレイヤーを隠すと思いましたが、さすが思い込みでしたね

今は、その「FXLayerIndex()」のメソッドをなんとなく直したけど、
直し方はちょっとひどいですから、今夜ちゃんと直してみます

にしても、その新しい [MyyVRCHelpers.cs](https://github.com/vr-voyage/vrchat-worldlock-autosetup/blob/25f74cf831a7aa3cdd939ef9e44d2c0b59780a92/Editor/MyyHelpers/MyyVRCHelpers.cs)で試すことをお願いできますか？
Unityで問題を解決したと思いますが、VRCHATではまだ試していませんね

**Comment by Yumuru** [comment]
試してみたらうまくいきましたー。
ありがとうございますっ

**Comment by vr-voyage** [comment]
試していただいてありがとうございます！

今回はコードの側でも問題がないと思いますから、[プレリリースしました](https://github.com/vr-voyage/vrchat-worldlock-autosetup/releases/tag/v1.4.1rc1)。
そして、テストしましたね
UnityでもVRCHATでも問題がなさそうです

不具合報告がない限り、明日でGithubとBoothにリリースしますね

**Comment by vr-voyage** [comment]
[リリースしました](https://github.com/vr-voyage/vrchat-worldlock-autosetup/releases/latest)！
[Boothにも](https://voyage-vrsns.booth.pm/items/3170932)

改めて、ご報告ありがとうございました！

今回の問題は解決されたと思いますから、そのチケットを閉じます。
同じ不具合に遭ったら、そのチケットを再開しておねがいます
